## [COLUMN Datatype List] 동일 DB Column Datatype 조회 - ARGS( ${COLUMN_NAME},${COLUMN_NAME2},${COLUMN_NAME3},${COLUMN_NAME4},${COLUMN_NAME5} )
SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, COLUMN_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME IN ('${COLUMN_NAME}','${COLUMN_NAME2}','${COLUMN_NAME3}','${COLUMN_NAME4}','${COLUMN_NAME5}')
ORDER BY 1,2,3;
