## [Cluster server List] Aurora MySQL Cluster의 서버 목록
SELECT SERVER_ID, SESSION_ID, LAST_UPDATE_TIMESTAMP, REPLICA_LAG_IN_MILLISECONDS, CPU
FROM INFORMATION_SCHEMA.REPLICA_HOST_STATUS
ORDER BY SERVER_ID;
