## [Database List] 데이터베이스 목록 조회
SELECT s.SCHEMA_NAME, MIN(s.DEFAULT_COLLATION_NAME) as DEFAULT_COLLATION_NAME,
       COUNT(t.TABLE_NAME) as TABLES, 
       IFNULL(SUM(t.DATA_LENGTH/1024/1024/1024),0) as DATA_LENGTH_GB, 
       IFNULL(SUM(t.INDEX_LENGTH/1024/1024/1024),0) as DATA_LENGTH_GB
FROM INFORMATION_SCHEMA.SCHEMATA s
  LEFT JOIN INFORMATION_SCHEMA.TABLES t ON t.TABLE_SCHEMA=s.SCHEMA_NAME
GROUP BY s.SCHEMA_NAME
ORDER BY s.SCHEMA_NAME;
