## [Database List] 데이터베이스 목록 조회
SELECT TABLE_SCHEMA, COUNT(*) as TABLES, SUM(DATA_LENGTH/1024/1024/1024) as DATA_LENGTH_GB, SUM(INDEX_LENGTH/1024/1024/1024) as DATA_LENGTH_GB 
FROM INFORMATION_SCHEMA.TABLES 
GROUP BY TABLE_SCHEMA 
ORDER BY TABLE_SCHEMA;
