## [Function List] 함수 목록 조회
SELECT ROUTINE_SCHEMA, ROUTINE_NAME 
FROM INFORMATION_SCHEMA.ROUTINES 
WHERE ROUTINE_TYPE='FUNCTION' 
  AND ROUTINE_SCHEMA='#{CURRENT_DB}' 
ORDER BY ROUTINE_SCHEMA, ROUTINE_NAME;
