## [Procedure List] 프로시져 목록 조회
SELECT ROUTINE_SCHEMA, ROUTINE_NAME 
FROM INFORMATION_SCHEMA.ROUTINES 
WHERE ROUTINE_TYPE='PROCEDURE' 
  AND ROUTINE_SCHEMA='#{CURRENT_DB}' 
ORDER BY ROUTINE_SCHEMA, ROUTINE_NAME;
