## [Processlist]  프로세스 목록 조회
SELECT ID, USER, HOST, DB, COMMAND, TIME, STATE, SUBSTRING(INFO, 1, 100) 
FROM INFORMATION_SCHEMA.PROCESSLIST 
WHERE COMMAND NOT IN ('Sleep','Daemon') 
ORDER BY TIME DESC;
