## [Table List] 테이블 목록 조회
SELECT TABLE_SCHEMA, TABLE_NAME, TABLE_ROWS, AVG_ROW_LENGTH, (DATA_LENGTH/1024/1024/1024) as DATA_LENGTH_GB, (INDEX_LENGTH/1024/1024/1024) as DATA_LENGTH_GB 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA='#{CURRENT_DB}' 
ORDER BY TABLE_SCHEMA, TABLE_NAME;
