## [Table Record Row] 테이블의 레코드 읽고 쓰기 수 - ARGS( ${TABLE_NAME} )
SELECT OBJECT_SCHEMA, OBJECT_NAME, COUNT_FETCH, COUNT_INSERT, COUNT_UPDATE, COUNT_DELETE
FROM performance_schema.table_io_waits_summary_by_table
WHERE OBJECT_SCHEMA='#{CURRENT_DB}' AND OBJECT_NAME LIKE '%${TABLE_NAME}%'
ORDER BY (COUNT_FETCH + COUNT_INSERT + COUNT_UPDATE + COUNT_DELETE) DESC ;
